// Query the GitHub commits API for the tip of `main` in the CaveCMS
// repo and decide whether it represents a newer revision than what's
// running locally.
//
// Strategy notes:
// - We pull `commits/main` (not `releases/latest`) because CaveCMS is
//   not currently tagging GitHub Releases — every push to main is the
//   shipped revision. When we start tagging, this can flip to
//   `/releases/latest` without changing the public shape returned here.
// - The endpoint is public for a public repo. If the user runs CaveCMS
//   from a private fork, set `GITHUB_PAT` and we add an Authorization
//   header. We never log or echo the token.
// - 5-minute in-memory cache keyed by `<owner>/<repo>` keeps repeated
//   "Check Now" clicks from hammering the GitHub API rate budget
//   (60 unauthenticated / 5000 authenticated reqs per hour).

export interface LatestRelease {
  /** Full git SHA of the tip of main. */
  sha: string
  /** ISO timestamp of the commit. */
  ts: string
  /** Commit message body (first line + any body). Truncated upstream. */
  changelog: string
  /** Heuristic: does the changelog mention security / CVE / vuln? */
  isSecurity: boolean
}

import { RELEASE_CHANGELOG_MAX_BYTES, RELEASE_FETCH_TIMEOUT_MS, UPDATE_CHECK_TTL_MS } from './constants'

interface CacheEntry {
  expiresAt: number
  value: LatestRelease
}

const CACHE = new Map<string, CacheEntry>()
const TTL_MS = UPDATE_CHECK_TTL_MS

// Test-only escape hatch — the unit suite needs to start from a clean
// cache between cases. NOT exported from the module's normal entry
// path; the suite imports it directly.
export function __resetCacheForTests(): void {
  CACHE.clear()
}

interface GithubCommitResponse {
  sha?: unknown
  commit?: {
    committer?: { date?: unknown } | null
    author?: { date?: unknown } | null
    message?: unknown
  }
}

export async function checkLatestRelease({
  owner,
  repo,
}: {
  owner: string
  repo: string
}): Promise<LatestRelease> {
  const cacheKey = `${owner}/${repo}`
  const hit = CACHE.get(cacheKey)
  if (hit && hit.expiresAt > Date.now()) {
    return hit.value
  }

  const url = `https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/commits/main`
  const headers: Record<string, string> = {
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    // User-Agent is required by the GitHub API. Identify ourselves so
    // GitHub support can correlate misbehaviour to the project, not the
    // generic Node fetch UA.
    'User-Agent': 'CaveCMS-Updates-Check',
  }
  // Optional PAT for private forks / higher rate budget. Read directly
  // from process.env (NOT lib/env.ts) so this module can be tested
  // standalone without dragging the full env validator in.
  const pat = process.env.GITHUB_PAT
  if (pat) {
    // Defensive PAT shape validation. GitHub PATs are alphanumeric +
    // underscore. Anything outside that (especially control bytes
    // like \r\n) could enable Authorization-header injection.
    if (!/^[A-Za-z0-9_]+$/.test(pat)) {
      throw new Error('github_pat_malformed')
    }
    headers.Authorization = `Bearer ${pat}`
  }

  const res = await fetch(url, {
    method: 'GET',
    headers,
    signal: AbortSignal.timeout(RELEASE_FETCH_TIMEOUT_MS),
  })

  if (!res.ok) {
    // Distinguish rate-limit (403/429 with x-ratelimit-remaining: 0)
    // from generic upstream failures so the check route can emit
    // operator-friendly copy ("GitHub is rate-limiting your IP —
    // try again in ~X minutes") instead of a flat "couldn't check
    // for updates". 404 for typo'd repo / private repo without PAT
    // gets its own class so configuration mistakes don't masquerade
    // as transient failures.
    if (res.status === 403 || res.status === 429) {
      const remaining = res.headers.get('x-ratelimit-remaining')
      if (remaining === '0' || res.status === 429) {
        const reset = res.headers.get('x-ratelimit-reset') ?? ''
        throw new Error(`github_rate_limited_${reset}`)
      }
    }
    if (res.status === 404) {
      throw new Error('github_repo_not_found')
    }
    throw new Error(`github_api_failed_${res.status}`)
  }

  const body = (await res.json()) as GithubCommitResponse
  const sha = typeof body.sha === 'string' ? body.sha : ''
  const dateRaw = body.commit?.committer?.date ?? body.commit?.author?.date
  const ts = typeof dateRaw === 'string' ? dateRaw : ''
  const message = typeof body.commit?.message === 'string' ? body.commit.message : ''

  if (!sha || !ts) {
    throw new Error('github_api_malformed')
  }

  // Trim the changelog at the configured cap so a runaway commit
  // message can't blow the response payload (one famous case: a
  // 60KB AUTOGENERATED block pasted into the commit body).
  const changelog = message.slice(0, RELEASE_CHANGELOG_MAX_BYTES)
  const isSecurity = /\b(?:cve-\d{4}-\d+|security|vulnerability|vuln(?:erab)?)\b/i.test(
    changelog,
  )

  const value: LatestRelease = { sha, ts, changelog, isSecurity }
  CACHE.set(cacheKey, { expiresAt: Date.now() + TTL_MS, value })
  return value
}
